@startwbs
!theme materia
skinparam BackgroundColor white
<style>
node {
    Padding 2
    Margin 3
    HorizontalAlignment center
    LineColor #9B231E
    LineThickness 2.0
    BackgroundColor #E53027
    FontColor white
    FontName Roboto
    FontStyle bold
    RoundCorner 3
    MaximumWidth 150
}
</style>

* FiLiP
** core
*** __init__.py
*** base_client.py \n class BaseClient
*** config.py \n class Settings
*** simple_query_language.py \n class SimpleQuery (maybe utils?)
** clients
*** __init__.py
*** client.py \n class Client
*** cb.py \n class ContextBrokerClient
*** timeseries.py \n class QuantumLeapClient
*** iota.py \n class IoTACLient
*** mqtt.py \n class MQTTClient
** models
*** __init__.py
*** general/base/core.py \n class FiwareHeader
*** iot.py \n class Device \n class DeviceGroup
*** context.py \n class ContextEntity \n class ContextAttribute etc.
*** subscriptions.py \n class Subscription
*** notifications.py \n class Notification and subsclasses
*** units.py \n class Unit
** utils
*** __init__.py
*** validators.py
*** datamodel_generator.py
*** token_manager.py
** external (no package)
*** units.hdf

@endwbs