# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/" # location of the setup.py
    schedule:
      interval: "monthly"
    allow:
      # Allow updates on explicit dependency
      - dependency-type: "direct"
    ignore:
      # Ignore updates for specific dependencies
      - dependency-name: "sphinx"
      - dependency-name: "autodoc-pydantic"
      - dependency-name: "sphinx-autobuild"
      - dependency-name: "m2r2"
      - dependency-name: "sphinx-rtd-theme"
      - dependency-name: "igraph"
      - dependency-name: "plotly"
      - dependency-name: "matplotlib"
      - dependency-name: "pre-commit"
    commit-message:
      prefix: "[pip dependency]"
    open-pull-requests-limit: 5
