# generated by datamodel-codegen:
#   filename:  IoTagent-node-lib-openapi.json
#   timestamp: 2020-12-04T10:12:01+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any


class Retrieveaserviceresponse(BaseModel):
    count: int
    services: List[Dict[str, Any]]


class Createaservicerequest(BaseModel):
    services: List[Dict[str, Any]]


class UpdateaserviceSubservicerequest(BaseModel):
    entity_type: str


class Retrievealldevicesresponse(BaseModel):
    count: int
    devices: List[Dict[str, Any]]


class Createadevicerequest(BaseModel):
    devices: List[Dict[str, Any]]


class Createadevice400response(BaseModel):
    reason: str


class Retrieveadeviceresponse(BaseModel):
    device_id: str
    protocol: str
    entity_name: str
    entity_type: str
    timezone: str
    attributes: List[Dict[str, Any]]
    static_attributes: List[Dict[str, Any]]


class Updateadevicerequest(BaseModel):
    entity_name: str
