name: Matrix Tests for Orion and IoT-Agent-JSON

on:
  push:
    branches:
      - "418-update-versions-for-fiware-ges"
  workflow_dispatch:

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        orion_version: ["3.8.0"]
        iot_json_version: ["1.25.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install
          pip install jinja2 pytest

      - name: Generate docker-compose.yml
        run: |
          python generate_compose.py ${{ matrix.orion_version }} ${{ matrix.iot_json_version }}

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Run Pytest
        run: |
          python -m unittest tests/clients/test_ngsi_v2_cb.py
          python -m pytest tests

#      - name: Archive test logs
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: logs-Orion=${{ matrix.orion_version }}__IoT=${{ matrix.iot_json_version }}
#          path: result.log

      - name: Tear down containers
        if: always()
        run: docker-compose down -v
