name: CI for FiLiP

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

  fiware_setup:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Clone FIWARE repository
        run: |
          git clone https://github.com/N5GEH/n5geh.platform.git

      - name: Start FIWARE services
        run: |
          cd n5geh.platform/v2
          docker compose up -d

      - name: Wait for FIWARE services to stabilize
        run: sleep 30

      - name: Verify FIWARE services
        run: curl -X GET "http://localhost:1026/version"

  test:
    runs-on: ubuntu-latest
    needs: fiware_setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          docker-compose run --rm orion bash -c "pytest tests || true"