name: Python Unit Tests

on:
  push:
    branches:
      - 315-Unittest-via-Github-actions
  pull_request:
    branches:
      - 315-Unittest-via-Github-actions

jobs:
  setup-python:
    name: Setup Python Versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Verify Python Installation
    - name: Verify Python Version
      run: |
        python --version
        pip --version

  install-dependencies:
    name: Install Dependencies
    needs: setup-python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -e .

  create-env:
    name: Create Test Environment
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Create .env File
    - name: Set up Test Environment
      run: |
        echo "LOG_LEVEL=INFO" >> FiLiP/tests/.env
        echo "CB_URL=http://localhost:1026" >> FiLiP/tests/.env
        echo "IOTA_JSON_URL=http://localhost:4041" >> FiLiP/tests/.env
        echo "IOTA_UL_URL=http://localhost:4061" >> FiLiP/tests/.env
        echo "QL_URL=http://localhost:8668" >> FiLiP/tests/.env
        echo "MQTT_BROKER_URL=mqtt://localhost:1883" >> FiLiP/tests/.env
        echo "FIWARE_SERVICE=filip" >> FiLiP/tests/.env
        echo "FIWARE_SERVICEPATH=/testing" >> FiLiP/tests/.env

  run-tests:
    name: Run Unit Tests
    needs: create-env
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        test-engine: ["PYTEST", "UNITTEST"]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install Test Engine
    - name: Install Test Engine
      run: |
        if [ "${{ matrix.test-engine }}" == "PYTEST" ]; then
          pip install pytest;
        fi

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        TEST_PATH="FiLiP/tests"
        if [ "${{ matrix.test-engine }}" == "PYTEST" ]; then 
          python -m pytest $TEST_PATH/; 
        else 
          python -m unittest discover --verbose $TEST_PATH "test_*.py"; 
        fi
